export interface Product {
  id: string;
  title: string;
  description: string;
  price: number;
  category: string;
  subcategory: string;
  images: string[];
  sizes: string[];
  colors: string[];
  material: string;
  features: string[];
  isFeatured?: boolean;
}

export const categories = [
  "Sign Boards & Letters",
  "Printing & Banners",
  "Accessories & Others"
];

export const products: Product[] = [
  {
    id: "product1",
    title: "Alluminium profile changeable directory board",
    description: "Premium Co sign material imported Alluminium profile, changeable name plate.cmyk uv print. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 1350,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product1/image copy 2.png","/products/product1/image copy 3.png","/products/product1/image copy 4.png","/products/product1/image copy.png","/products/product1/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: true
  },
  {
    id: "product2",
    title: "Ss letter with blue color",
    description: "Premium Original ss 304... Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 290,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product2/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: true
  },
  {
    id: "product3",
    title: "Ss letter back side 10mm acrylic and ss dot cutting",
    description: "Premium Original ss 304,cnc dot cutting, base 10mm acrylic imported and led 5 year warranty.. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 320,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product3/image copy 2.png","/products/product3/image copy 3.png","/products/product3/image copy 4.png","/products/product3/image copy.png","/products/product3/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: true
  },
  {
    id: "product4",
    title: "Ss with 10mm acrylic glow sign letter",
    description: "Premium Original ss 304, imported acrylic, brand led 5 year warranty. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 280,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product4/image copy 2.png","/products/product4/image copy 3.png","/products/product4/image copy 4.png","/products/product4/image copy 5.png","/products/product4/image copy 6.png","/products/product4/image copy.png","/products/product4/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: true
  },
  {
    id: "product5",
    title: "Led board",
    description: "Premium Led board 5 year warranty. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 160,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product5/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product6",
    title: "Acp Panel  Board",
    description: "Premium PVDF silver texture acp panel with 2 layer uv printing SP011. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 400,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product6/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product7",
    title: "all type led sign board manufacturing",
    description: "Premium all type. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 1,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product7/image copy 2.png","/products/product7/image copy 3.png","/products/product7/image copy 4.png","/products/product7/image copy 5.png","/products/product7/image copy 6.png","/products/product7/image copy 7.png","/products/product7/image copy 8.png","/products/product7/image copy 9.png","/products/product7/image copy.png","/products/product7/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product8",
    title: "led board manufacturing pune 5 year warranty",
    description: "Premium led 5 year warranty. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 400,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product8/image copy 2.png","/products/product8/image copy 3.png","/products/product8/image copy 4.png","/products/product8/image copy 5.png","/products/product8/image copy 6.png","/products/product8/image copy 7.png","/products/product8/image copy 8.png","/products/product8/image copy 9.png","/products/product8/image copy.png","/products/product8/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product9",
    title: "tag , bach printing",
    description: "Premium all type tag and bach printing service tb. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 15,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product9/image copy 2.png","/products/product9/image copy 3.png","/products/product9/image copy 4.png","/products/product9/image copy 5.png","/products/product9/image copy.png","/products/product9/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product10",
    title: "clip on freme with uv translit backlit print",
    description: "Premium 2 year warranty cof. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 780,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product10/image copy 2.png","/products/product10/image copy 3.png","/products/product10/image copy.png","/products/product10/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product11",
    title: "Home name plate",
    description: "Premium Acrylic box name plate with led glow sign.. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 3000,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product11/image copy 2.png","/products/product11/image copy 3.png","/products/product11/image copy.png","/products/product11/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product12",
    title: "SS letter with back 10 mm acrylic letter",
    description: "Premium Original ss use code 304.and 10mm 040 acrylic with led 5 year warranty power supply 2 year warranty.. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 260,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product12/image copy 2.png","/products/product12/image copy 3.png","/products/product12/image copy 4.png","/products/product12/image copy 5.png","/products/product12/image copy.png","/products/product12/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product13",
    title: "Led board",
    description: "Premium 450 per square feet start. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 450,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product13/image copy 2.png","/products/product13/image copy.png","/products/product13/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product14",
    title: "Id card printing",
    description: "Premium Pvc card 1.02mm printing and logo ingreving and less print satin material available size 16mm,18mm,20mm. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 70,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product14/image copy 2.png","/products/product14/image copy 3.png","/products/product14/image copy.png","/products/product14/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product15",
    title: "Sign name board",
    description: "Premium Acrylic material and Laser cutting,led use in board. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 500,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product15/image copy 2.png","/products/product15/image copy.png","/products/product15/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product16",
    title: "Rolling standy board",
    description: "Premium Alluminium base rolling standy and platinum black back flex 260 gsm.printing KMC pro ink Polo turbo machine.. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 1250,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product16/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product17",
    title: "Vinyl printing eco solvent",
    description: "Premium Vinyl printing 120 mic .mimaki and Roland machine printing cartridges ink.8000 rs lifter cartage.. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 25,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product17/image copy 2.png","/products/product17/image copy 3.png","/products/product17/image copy 4.png","/products/product17/image copy 5.png","/products/product17/image copy 6.png","/products/product17/image copy 7.png","/products/product17/image copy 8.png","/products/product17/image copy 9.png","/products/product17/image copy.png","/products/product17/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product18",
    title: "Star flex printing",
    description: "Premium Original star flex printing 4 pass printing.polo turbo machine printing KMC pro ink use in Printing.2year outdoor warranty.. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 18,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product18/image copy 2.png","/products/product18/image copy 3.png","/products/product18/image copy 4.png","/products/product18/image copy 5.png","/products/product18/image copy 6.png","/products/product18/image copy 7.png","/products/product18/image copy.png","/products/product18/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product19",
    title: "Flex printing services",
    description: "Premium Platinum flex printing 240 gsm . machine polo turbo KMC pro ink use.kmc Pro ink price -1700 litter. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 7,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product19/image copy 2.png","/products/product19/image copy.png","/products/product19/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product20",
    title: "Wooden Easel stand",
    description: "Premium 1 11. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 1250,
    category: "Accessories & Others",
    subcategory: "Standard",
    images: ["/products/product20/image copy 2.png","/products/product20/image copy 3.png","/products/product20/image copy 4.png","/products/product20/image copy 5.png","/products/product20/image copy 6.png","/products/product20/image copy 7.png","/products/product20/image copy 8.png","/products/product20/image copy 9.png","/products/product20/image copy.png","/products/product20/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product21",
    title: "Led sign board.",
    description: "Premium Led 5 year warranty and power supply 2 year warranty https://sanaviprintpoint.co.in/ 14. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 160,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product21/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product22",
    title: "Orignal star backlight uv printing with 5 year board warranty",
    description: "Premium Orignal star backlight and led trip use in board .led 5 year warranty and power supply 2 year warranty. https://sanaviprintpoint.co.in/ 13. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 450,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product22/image copy 2.png","/products/product22/image copy 3.png","/products/product22/image copy 4.png","/products/product22/image copy.png","/products/product22/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product23",
    title: "Led glow sign board manufacturing wholesale",
    description: "Premium Led sunsign 5 year warranty and power supply 2 year warranty.impoted acrylic and board one year serv https://sanaviprintpoint.co.in/ 12. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 160,
    category: "Sign Boards & Letters",
    subcategory: "Standard",
    images: ["/products/product23/image copy 2.png","/products/product23/image copy 3.png","/products/product23/image copy 4.png","/products/product23/image copy 5.png","/products/product23/image copy.png","/products/product23/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
  {
    id: "product24",
    title: "Flex printing 240 gsm rate only 7 rs square feet",
    description: "Premium 240 gsm KMC PRO INK use in printing https://sanaviprintpoint.co.in/ Flex. Crafted with top-quality materials to ensure longevity and a professional finish. Perfect for businesses looking to enhance their visibility with top-tier signage and branding solutions.",
    price: 7,
    category: "Printing & Banners",
    subcategory: "Standard",
    images: ["/products/product24/image copy 2.png","/products/product24/image copy.png","/products/product24/image.png"],
    sizes: ["Standard"],
    colors: ["Full Color"],
    material: "Standard Material",
    features: ["High Quality", "Durable"],
    isFeatured: false
  },
];