export interface Product {
  id: string;
  title: string;
  description: string;
  category: string;
  images: string[];
  isFeatured?: boolean;
  
  // B2B Specification Driven Properties
  material: string;
  thickness: string;
  lightingType: "None" | "LED Backlit" | "LED Frontlit" | "Neon" | "Edge-lit";
  installationType: string;
  durability: "Indoor/Outdoor" | "Indoor Only" | "Outdoor Only";
  pricingUnit: "sqft" | "inch" | "fixed" | "unit";
  basePrice: number; // Price per unit/sqft/inch
  minimumOrder: string;
  turnaroundTime: string;
}

export const categories = [
  "Signboards",
  "Flex & Vinyl Printing",
  "ACP Panels",
  "LED Boards",
  "Branding & Accessories",
  "3D Acrylic Letters"
];

export const products: Product[] = [
  {
    id: "product1",
    title: "Alluminium profile changeable directory board",
    description: "Premium Alluminium profile changeable directory board. Co sign material imported Alluminium profile, changeable name plate.cmyk uv print",
    category: "Flex & Vinyl Printing",
    images: ["/products/product1/image copy 2.png","/products/product1/image copy 3.png","/products/product1/image copy 4.png","/products/product1/image copy.png","/products/product1/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 1350,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: true
  },
  {
    id: "product2",
    title: "Ss letter with blue color",
    description: "Premium Ss letter with blue color. Original ss 304..",
    category: "3D Acrylic Letters",
    images: ["/products/product2/image.png"],
    material: "SS 304 & Acrylic",
    thickness: "Custom Depth",
    lightingType: "None",
    installationType: "Stud Mount",
    durability: "Indoor/Outdoor",
    pricingUnit: "inch",
    basePrice: 290,
    minimumOrder: "10 Inches",
    turnaroundTime: "3-5 Business Days",
    isFeatured: true
  },
  {
    id: "product3",
    title: "Ss letter back side 10mm acrylic and ss dot cutting",
    description: "Premium Ss letter back side 10mm acrylic and ss dot cutting. Original ss 304,cnc dot cutting, base 10mm acrylic imported and led 5 year warranty.",
    category: "3D Acrylic Letters",
    images: ["/products/product3/image copy 2.png","/products/product3/image copy 3.png","/products/product3/image copy 4.png","/products/product3/image copy.png","/products/product3/image.png"],
    material: "SS 304 & Acrylic",
    thickness: "Custom Depth",
    lightingType: "LED Backlit",
    installationType: "Stud Mount",
    durability: "Indoor/Outdoor",
    pricingUnit: "inch",
    basePrice: 320,
    minimumOrder: "10 Inches",
    turnaroundTime: "3-5 Business Days",
    isFeatured: true
  },
  {
    id: "product4",
    title: "Ss with 10mm acrylic glow sign letter",
    description: "Premium Ss with 10mm acrylic glow sign letter. Original ss 304, imported acrylic, brand led 5 year warranty",
    category: "3D Acrylic Letters",
    images: ["/products/product4/image copy 2.png","/products/product4/image copy 3.png","/products/product4/image copy 4.png","/products/product4/image copy 5.png","/products/product4/image copy 6.png","/products/product4/image copy.png","/products/product4/image.png"],
    material: "SS 304 & Acrylic",
    thickness: "Custom Depth",
    lightingType: "LED Backlit",
    installationType: "Stud Mount",
    durability: "Indoor/Outdoor",
    pricingUnit: "inch",
    basePrice: 280,
    minimumOrder: "10 Inches",
    turnaroundTime: "3-5 Business Days",
    isFeatured: true
  },
  {
    id: "product5",
    title: "Led board",
    description: "Premium Led board. Led board 5 year warranty",
    category: "LED Boards",
    images: ["/products/product5/image.png"],
    material: "Acrylic / Metal Frame",
    thickness: "Custom",
    lightingType: "LED Frontlit",
    installationType: "Wall Mounted",
    durability: "Indoor/Outdoor",
    pricingUnit: "sqft",
    basePrice: 160,
    minimumOrder: "10 SqFt",
    turnaroundTime: "3-5 Business Days",
    isFeatured: false
  },
  {
    id: "product6",
    title: "Acp Panel  Board",
    description: "Premium Acp Panel  Board. PVDF silver texture acp panel with 2 layer uv printing SP011",
    category: "Flex & Vinyl Printing",
    images: ["/products/product6/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 400,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product7",
    title: "all type led sign board manufacturing",
    description: "Premium all type led sign board manufacturing. all type",
    category: "LED Boards",
    images: ["/products/product7/image copy 2.png","/products/product7/image copy 3.png","/products/product7/image copy 4.png","/products/product7/image copy 5.png","/products/product7/image copy 6.png","/products/product7/image copy 7.png","/products/product7/image copy 8.png","/products/product7/image copy 9.png","/products/product7/image copy.png","/products/product7/image.png"],
    material: "Acrylic / Metal Frame",
    thickness: "Custom",
    lightingType: "LED Frontlit",
    installationType: "Wall Mounted",
    durability: "Indoor/Outdoor",
    pricingUnit: "sqft",
    basePrice: 1,
    minimumOrder: "10 SqFt",
    turnaroundTime: "3-5 Business Days",
    isFeatured: false
  },
  {
    id: "product8",
    title: "led board manufacturing pune 5 year warranty",
    description: "Premium led board manufacturing pune 5 year warranty. led 5 year warranty",
    category: "LED Boards",
    images: ["/products/product8/image copy 2.png","/products/product8/image copy 3.png","/products/product8/image copy 4.png","/products/product8/image copy 5.png","/products/product8/image copy 6.png","/products/product8/image copy 7.png","/products/product8/image copy 8.png","/products/product8/image copy 9.png","/products/product8/image copy.png","/products/product8/image.png"],
    material: "Acrylic / Metal Frame",
    thickness: "Custom",
    lightingType: "LED Frontlit",
    installationType: "Wall Mounted",
    durability: "Indoor/Outdoor",
    pricingUnit: "sqft",
    basePrice: 400,
    minimumOrder: "10 SqFt",
    turnaroundTime: "3-5 Business Days",
    isFeatured: false
  },
  {
    id: "product9",
    title: "tag , bach printing",
    description: "Premium tag , bach printing. all type tag and bach printing service tb",
    category: "Flex & Vinyl Printing",
    images: ["/products/product9/image copy 2.png","/products/product9/image copy 3.png","/products/product9/image copy 4.png","/products/product9/image copy 5.png","/products/product9/image copy.png","/products/product9/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 15,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product10",
    title: "clip on freme with uv translit backlit print",
    description: "Premium clip on freme with uv translit backlit print. 2 year warranty cof",
    category: "Flex & Vinyl Printing",
    images: ["/products/product10/image copy 2.png","/products/product10/image copy 3.png","/products/product10/image copy.png","/products/product10/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 780,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product11",
    title: "Home name plate",
    description: "Premium Home name plate. Acrylic box name plate with led glow sign.",
    category: "LED Boards",
    images: ["/products/product11/image copy 2.png","/products/product11/image copy 3.png","/products/product11/image copy.png","/products/product11/image.png"],
    material: "Acrylic / Metal Frame",
    thickness: "Custom",
    lightingType: "LED Frontlit",
    installationType: "Wall Mounted",
    durability: "Indoor/Outdoor",
    pricingUnit: "sqft",
    basePrice: 3000,
    minimumOrder: "10 SqFt",
    turnaroundTime: "3-5 Business Days",
    isFeatured: false
  },
  {
    id: "product12",
    title: "SS letter with back 10 mm acrylic letter",
    description: "Premium SS letter with back 10 mm acrylic letter. Original ss use code 304.and 10mm 040 acrylic with led 5 year warranty power supply 2 year warranty.",
    category: "3D Acrylic Letters",
    images: ["/products/product12/image copy 2.png","/products/product12/image copy 3.png","/products/product12/image copy 4.png","/products/product12/image copy 5.png","/products/product12/image copy.png","/products/product12/image.png"],
    material: "SS 304 & Acrylic",
    thickness: "Custom Depth",
    lightingType: "LED Backlit",
    installationType: "Stud Mount",
    durability: "Indoor/Outdoor",
    pricingUnit: "inch",
    basePrice: 260,
    minimumOrder: "10 Inches",
    turnaroundTime: "3-5 Business Days",
    isFeatured: false
  },
  {
    id: "product13",
    title: "Led board",
    description: "Premium Led board. 450 per square feet start",
    category: "LED Boards",
    images: ["/products/product13/image copy 2.png","/products/product13/image copy.png","/products/product13/image.png"],
    material: "Acrylic / Metal Frame",
    thickness: "Custom",
    lightingType: "LED Frontlit",
    installationType: "Wall Mounted",
    durability: "Indoor/Outdoor",
    pricingUnit: "sqft",
    basePrice: 450,
    minimumOrder: "10 SqFt",
    turnaroundTime: "3-5 Business Days",
    isFeatured: false
  },
  {
    id: "product14",
    title: "Id card printing",
    description: "Premium Id card printing. Pvc card 1.02mm printing and logo ingreving and less print satin material available size 16mm,18mm,20mm",
    category: "Flex & Vinyl Printing",
    images: ["/products/product14/image copy 2.png","/products/product14/image copy 3.png","/products/product14/image copy.png","/products/product14/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 70,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product15",
    title: "Sign name board",
    description: "Premium Sign name board. Acrylic material and Laser cutting,led use in board",
    category: "LED Boards",
    images: ["/products/product15/image copy 2.png","/products/product15/image copy.png","/products/product15/image.png"],
    material: "Acrylic / Metal Frame",
    thickness: "Custom",
    lightingType: "LED Frontlit",
    installationType: "Wall Mounted",
    durability: "Indoor/Outdoor",
    pricingUnit: "sqft",
    basePrice: 500,
    minimumOrder: "10 SqFt",
    turnaroundTime: "3-5 Business Days",
    isFeatured: false
  },
  {
    id: "product16",
    title: "Rolling standy board",
    description: "Premium Rolling standy board. Alluminium base rolling standy and platinum black back flex 260 gsm.printing KMC pro ink Polo turbo machine.",
    category: "Flex & Vinyl Printing",
    images: ["/products/product16/image.png"],
    material: "240 GSM Flex / Star Flex",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 1250,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product17",
    title: "Vinyl printing eco solvent",
    description: "Premium Vinyl printing eco solvent. Vinyl printing 120 mic .mimaki and Roland machine printing cartridges ink.8000 rs lifter cartage.",
    category: "Flex & Vinyl Printing",
    images: ["/products/product17/image copy 2.png","/products/product17/image copy 3.png","/products/product17/image copy 4.png","/products/product17/image copy 5.png","/products/product17/image copy 6.png","/products/product17/image copy 7.png","/products/product17/image copy 8.png","/products/product17/image copy 9.png","/products/product17/image copy.png","/products/product17/image.png"],
    material: "120 Mic Vinyl",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Indoor Only",
    pricingUnit: "sqft",
    basePrice: 25,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: true
  },
  {
    id: "product18",
    title: "Star flex printing",
    description: "Premium Star flex printing. Original star flex printing 4 pass printing.polo turbo machine printing KMC pro ink use in Printing.2year outdoor warranty.",
    category: "Flex & Vinyl Printing",
    images: ["/products/product18/image copy 2.png","/products/product18/image copy 3.png","/products/product18/image copy 4.png","/products/product18/image copy 5.png","/products/product18/image copy 6.png","/products/product18/image copy 7.png","/products/product18/image copy.png","/products/product18/image.png"],
    material: "240 GSM Flex / Star Flex",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 18,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product19",
    title: "Flex printing services",
    description: "Premium Flex printing services. Platinum flex printing 240 gsm . machine polo turbo KMC pro ink use.kmc Pro ink price -1700 litter",
    category: "Flex & Vinyl Printing",
    images: ["/products/product19/image copy 2.png","/products/product19/image copy.png","/products/product19/image.png"],
    material: "240 GSM Flex / Star Flex",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 7,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: true
  },
  {
    id: "product20",
    title: "Wooden Easel stand",
    description: "Premium Wooden Easel stand. 1 11",
    category: "Branding & Accessories",
    images: ["/products/product20/image copy 2.png","/products/product20/image copy 3.png","/products/product20/image copy 4.png","/products/product20/image copy 5.png","/products/product20/image copy 6.png","/products/product20/image copy 7.png","/products/product20/image copy 8.png","/products/product20/image copy 9.png","/products/product20/image copy.png","/products/product20/image.png"],
    material: "Wood",
    thickness: "Custom",
    lightingType: "None",
    installationType: "Wall Mounted",
    durability: "Indoor/Outdoor",
    pricingUnit: "unit",
    basePrice: 1250,
    minimumOrder: "100 Units",
    turnaroundTime: "2-4 Business Days",
    isFeatured: false
  },
  {
    id: "product21",
    title: "Led sign board.",
    description: "Premium Led sign board.. Led 5 year warranty and power supply 2 year warranty https://sanaviprintpoint.co.in/ 14",
    category: "Flex & Vinyl Printing",
    images: ["/products/product21/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 160,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product22",
    title: "Orignal star backlight uv printing with 5 year board warranty",
    description: "Premium Orignal star backlight uv printing with 5 year board warranty. Orignal star backlight and led trip use in board .led 5 year warranty and power supply 2 year warranty. https://sanaviprintpoint.co.in/ 13",
    category: "Flex & Vinyl Printing",
    images: ["/products/product22/image copy 2.png","/products/product22/image copy 3.png","/products/product22/image copy 4.png","/products/product22/image copy.png","/products/product22/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 450,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product23",
    title: "Led glow sign board manufacturing wholesale",
    description: "Premium Led glow sign board manufacturing wholesale. Led sunsign 5 year warranty and power supply 2 year warranty.impoted acrylic and board one year serv https://sanaviprintpoint.co.in/ 12",
    category: "Flex & Vinyl Printing",
    images: ["/products/product23/image copy 2.png","/products/product23/image copy 3.png","/products/product23/image copy 4.png","/products/product23/image copy 5.png","/products/product23/image copy.png","/products/product23/image.png"],
    material: "Printing Substrate",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 160,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
  {
    id: "product24",
    title: "Flex printing 240 gsm rate only 7 rs square feet",
    description: "Premium Flex printing 240 gsm rate only 7 rs square feet. 240 gsm KMC PRO INK use in printing https://sanaviprintpoint.co.in/ Flex",
    category: "Flex & Vinyl Printing",
    images: ["/products/product24/image copy 2.png","/products/product24/image copy.png","/products/product24/image.png"],
    material: "240 GSM Flex / Star Flex",
    thickness: "Standard",
    lightingType: "None",
    installationType: "Eyelets / Adhesive Application",
    durability: "Outdoor Only",
    pricingUnit: "sqft",
    basePrice: 7,
    minimumOrder: "50 SqFt",
    turnaroundTime: "1-3 Business Days",
    isFeatured: false
  },
];
